{% set name = "python-crontab" %}
{% set version = "2.3.7" %}
{% set sha256 = "21bf01edd59a7357cdc9b1d911b16430499bf51172dd8c72d0c985c652f14057" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil

test:
  imports:
    - crontab

about:
  home: https://github.com/doctormo/python-crontab
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: 'Crontab module for reading and writing crontab files and accessing the system cron automatically and simply using a direct API.'

extra:
  recipe-maintainers:
    - scopatz
