{% set name = "python-crontab" %}
{% set version = "3.0.0" %}
{% set sha256 = "79fb7465039ddfd4fb93d072d6ee0d45c1ac8bf1597f0686ea14fd4361dba379" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil

test:
  imports:
    - crontab

about:
  home: https://github.com/doctormo/python-crontab
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: Crontab module for reading and writing crontab files and accessing the system cron automatically and simply using a direct API.

extra:
  recipe-maintainers:
    - scopatz
    - jan-janssen
